name: Keep Tezt Alive
on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    name: Ping Tezt
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: |
          curl -X GET https://tezt.ai -I \
          -H "User-Agent: GitHub-Ping-Action" \
          -H "Accept: */*"
